version: '3'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/traefik"
      - "traefik.port=8000"
      - "traefik.backend=traefik"
      - "traefik.frontend.entryPoints=http"

networks:
  proxy:
    name: proxy
